#!/usr/bin/env python

import argparse
import importlib
from pathlib import Path
import logging

p = argparse.ArgumentParser()
p.add_argument("day", type=int)
p.add_argument("--a")
p.add_argument("--b")
p.add_argument("-v", type=int, default=0)
args = p.parse_args()

level_map = {
        0: logging.CRITICAL,
        1: logging.ERROR,
        2: logging.WARNING,
        3: logging.INFO,
        4: logging.DEBUG
}

logging.basicConfig(level=level_map[args.v])

module_name = f'day{args.day:02}'

m = importlib.import_module(module_name)

input_a = Path(args.a or f'day{args.day:02}.input')
if input_a.exists():
    with input_a.open() as f:
        answer = m.main_a(f)
        print(f'Part a: {answer}')

input_b = Path(args.b or f'day{args.day:02}.input')
if input_b.exists():
    with input_b.open() as f:
        answer = m.main_b(f)
        print(f'Part b: {answer}')
